# Generated by Django 2.2.11 on 2020-03-31 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0004_auto_20200331_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='alunos',
            field=models.ManyToManyField(related_name='usuario', through='cursos.AlunoCurso', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alunocurso',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_curso', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alunocurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_aluno', to='cursos.Curso'),
        ),
    ]
